-- hotel.statistiche definition

CREATE TABLE `statistiche` (
  `id` int NOT NULL AUTO_INCREMENT,
  `data_rilevamento` date NOT NULL,
  `num_clienti` int NOT NULL,
  `num_camere_totali` int NOT NULL,
  `num_camere_disponibili` int NOT NULL,
  `num_prenotazioni_totali` int NOT NULL,
  `num_prenotazioni_concluse` int NOT NULL,
  `num_prenotazioni_annullate` int NOT NULL,
  `num_entrate` int NOT NULL,
  `num_uscite` int NOT NULL,
  `importo_entrate` decimal(8,2) NOT NULL,
  `importo_uscite` decimal(8,2) NOT NULL,
  `tassa_soggiorno_totale` decimal(8,2) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `num_clienti` (`num_clienti`),
  KEY `num_camere_totali` (`num_camere_totali`),
  KEY `num_camere_disponibili` (`num_camere_disponibili`),
  KEY `num_prenotazioni_totali` (`num_prenotazioni_totali`),
  KEY `num_prenotazioni_concluse` (`num_prenotazioni_concluse`),
  KEY `num_prenotazioni_annullate` (`num_prenotazioni_annullate`),
  KEY `num_entrate` (`num_entrate`),
  KEY `num_uscite` (`num_uscite`),
  CONSTRAINT `statistiche_ibfk_1` FOREIGN KEY (`num_clienti`) REFERENCES `clienti` (`id`),
  CONSTRAINT `statistiche_ibfk_2` FOREIGN KEY (`num_camere_totali`) REFERENCES `camere` (`id`),
  CONSTRAINT `statistiche_ibfk_3` FOREIGN KEY (`num_camere_disponibili`) REFERENCES `camere` (`id`),
  CONSTRAINT `statistiche_ibfk_4` FOREIGN KEY (`num_prenotazioni_totali`) REFERENCES `prenotazioni` (`id`),
  CONSTRAINT `statistiche_ibfk_5` FOREIGN KEY (`num_prenotazioni_concluse`) REFERENCES `prenotazioni` (`id`),
  CONSTRAINT `statistiche_ibfk_6` FOREIGN KEY (`num_prenotazioni_annullate`) REFERENCES `prenotazioni` (`id`),
  CONSTRAINT `statistiche_ibfk_7` FOREIGN KEY (`num_entrate`) REFERENCES `entrate` (`id`),
  CONSTRAINT `statistiche_ibfk_8` FOREIGN KEY (`num_uscite`) REFERENCES `uscite` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;